### ISSUE TITLE
Inputs in subfolders produce wrong errors

### ISSUE THREAD

**Issue by JulianGoeltz** [j2kun/chktex-action#6]
When using `\input` in a subfolder, this chktex-action will fail, because the filename will not be found. 
Suppose the following file structure:
```
main.tex
A/a1.tex
A/a2.tex
```
where `main.tex` does `\input{A/a1.tex}`, and in turn `A/a1.tex` does `\input{A/a2.tex}`. This will compile fine, and running `chktex` on any file from the main folder will succeed.

In the current implementation of this action, however, the following [line](https://github.com/j2kun/chktex-action/blob/a2a6a3f13ae91acd27a6d094a751dec80c767832/run_action.py#L57) leads to an error, as the file is checked from within the subfolder.
This issue is trivially fixed by [deleting the lines](https://github.com/JulianGoeltz/chktex-action/commit/7bf1208f067585c7b9ad1d339f9c0d22ab4ef664) but in cases where the main `tex` file is in a subfolder, this will lead to errors in turn.

Is there a way to detect the 'main' `tex` file for a given file and only check from the respective working directory, or is there no way to prevent those errors (other than having `\input`s only in the main file)?

**Comment by j2kun** [comment]
This seems like a bit of a chicken and egg problem. My gut says the project should be configured such that chktex is always run from the base directory of the repository, and a configuration can be added (say, via an environment variable) that changes the working directory for all invocations of chktex (say, if the tex "part" of a project is entirely contained in one subdirectory).

I think that would solve your issue, yes?

I could implement this, but ideally I would have the time to write some tests for this project, since it's been a while since I touched it and I would hate to break things.

**Comment by JulianGoeltz** [comment]
Thank you for the fast response. 
If I understand your proposal correctly, there are other cases that will fail: I discovered the issue in a project where there is a figure that is created from latex as well, and it is included as a `pdf`. If one checks that from the root folder errors will come up (it also uses `input`s).
Ideally one could configure the action to list the main `tex` files, and let `chktex` follow the `input`s of those files, I think. Then there is only the problem of defining a sensible default in the absence of a list of files.

For my project I circumvented the issue by moving the `input`s into the main file, so please don't feel pressured and proceed as you wish.

**Comment by j2kun** [comment]
Another good idea. I somewhat worry in that case, that a user may forget to include some files and be surprised when they are not linted. By contrast, a normal programming language linter lints every file, and linting is generally understood to be local to the file in question. chktex's eager input mechanism seems to me to go against the grain in that respect. I don't know of a case in which not \inputting a file would result in chktex failing where it would otherwise pass...

I also looked up the [documentation](http://tex.loria.fr/outils/ChkTeX.pdf) for chktex, and if you specify --inputfiles=0, chktex will ignore the input statements. Perhaps the easiest route is to enable that flag in your project's `.chktexrc`, and/or I can make it the default for the action.

**Comment by JulianGoeltz** [comment]
I think due to your script checking every file it would be the sensible choice to enable it by default, yes.
Your worries about my idea are correct, I think using the `--inputfiles` flag is the best option.
Thanks again

**Comment by j2kun** [comment]
Fixed in v1.0.3.
